# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = [
#     "f5-tts",
#     "torch>=2.8,<3.0",
#     "torchaudio>=2.8",
#     "soundfile>=0.13",
#     "pydub>=0.25.1",
#     "pyyaml>=6.0",
# ]
# ///
"""F5-TTS sample generator — zero-shot voice cloning from the Kokoro ref clip.

WEIGHTS ARE CC-BY-NC: fine for this evaluation, must be flagged before any
shipped use. Prompt is scratch/tts-samples/ref.wav + REF_TEXT (our own text,
generated by kokoro.py --emit-ref).
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import REF_TEXT, REF_WAV, run_engine  # noqa: E402


def load_model():
    if not REF_WAV.exists():
        raise RuntimeError(f"reference clip missing: {REF_WAV} — run `uv run scripts/audio/samples/kokoro.py --emit-ref` first")
    from f5_tts.api import F5TTS

    print("[f5tts] loading F5TTS …", flush=True)
    return F5TTS()


def synthesize(model, text: str):
    wav, sr, _ = model.infer(
        ref_file=str(REF_WAV),
        ref_text=REF_TEXT,
        gen_text=text,
        seed=42,
    )
    return np.asarray(wav, dtype=np.float32).squeeze(), sr


if __name__ == "__main__":
    sys.exit(
        run_engine(
            "f5tts",
            load_model,
            synthesize,
            chunk_chars=800,
            license="CC-BY-NC-4.0 weights — evaluation only, do not ship",
            voice="zero-shot clone of Kokoro af_heart ref clip",
            notes="F5TTS_Base (flow-matching transformer). Voice-cloned from the Kokoro reference so timbre is comparable, not model-native.",
        )
    )
